#!/bin/zsh

# Aliases
## emacs
alias emdae='emacs --daemon'
alias emkill='emacsclient -e "(kill-emacs)"'
alias emstart='emacsclient -c -a emacs'

## grep
# alias ag='grep --color-match="1;31"'
# alias grep='ag --color-match="1;31"'
alias grep='grep --color=auto'

## zshell
alias zsrc='source $ZDOTDIR/.zshrc'

## ls
alias ll='ls -lv --color=auto'
alias la='ls -lAv --sort=extension --group-directories-first --color=auto'

## pip3
alias pip='pip3'

# ## Kubernetes & Minikube
# alias mk="minikube kubectl --"
# alias k="kubectl"
# source <(kubectl completion zsh)

# ## the-fuck
# eval $(thefuck --alias)

## youtube-dl
alias ytmeta='yt-dlp --add-metadata -i'
alias ytsound='yt-dlp -x -f bestaudio/best'
